### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by The4codeblocks** [The4codeblocks/compression#1]
Did take a look at code, there seems to be some issues like at least polluting global namespace and overriding table.copy with implementation that yields different results.

Should at least fix that but yeah I'm not sure I get it, is it at its core supposed to be like storage expansion for selected nodes or is there more?

I mean there should be some good reason to install it as it is going to register some new nodes, depending on conf  but seems like some 10 per type or so by default.

_Originally posted by @S-S-X in https://github.com/pandorabox-io/in-game/issues/356#issuecomment-1660924101_

**Comment by S-S-X** [comment]
Most of it in compression_api but few globals that should be locals here too, should be fairly simple stuff to address anyway if just making most stuff local (minetest engine should also give some warnings in logs/console about these).

**Comment by The4codeblocks** [comment]
> Most of it in compression_api but few globals that should be locals here too, should be fairly simple stuff to address anyway if just making most stuff local (minetest engine should also give some warnings in logs/console about these).

Fewer globals to restrict than expected.
